site_name: Money Waffle
theme:
  name: terminal
  font:
    # text: Lora
    text: 'Noto Serif'
    code: Mulish
plugins:
  - md-to-html
  - search

extra_javascript:
  - https://code.highcharts.com/highcharts.js
  - https://code.highcharts.com/modules/exporting.js
  - https://code.highcharts.com/modules/export-data.js
  - https://code.highcharts.com/modules/accessibility.js
  - scripts/load_scripts.js

extra_css:
  - css/highcharts.css

copyright: Copyright 2024 MoneyWaffle.com. All rights reserved.
