name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: gh-pages
      TEMP_DIR: /tmp/site
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: >
          pip install mkdocs-material \
                      mkdocs-terminal \
                      mkdocs-charts-plugin \
                      mkdocs-cinder \
                      mkdocs-simple-blog \
                      mkdocs-bootstrap386 \
                      mkdocs-minify-plugin \
                      python-markdown-math \
                      mkdocs-nav-weight
      # - run: mkdocs gh-deploy --force
      - name: Build EN site
        run: |
          mkdocs build
      - name: Move files to temp dir
        run: mv site $TEMP_DIR
      - name: Push to target branch
        run: |
          git fetch
          git checkout $TARGET_BRANCH
          rm -rf *
          mv $TEMP_DIR/* .
          git add -A
          git diff-index --quiet HEAD || git commit -am "Deploy to target branch"
          git push origin $TARGET_BRANCH